import React, { useMemo } from 'react';
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowDown,
  IconArrowUp,
  IconAward,
  IconBell,
  IconBellOff,
  IconBook,
  IconBriefcase,
  IconBuildingBank,
  IconBulb,
  IconCalendarCheck,
  IconCalendarMonth,
  IconCalendarRepeat,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconClipboardCheck,
  IconClipboardList,
  IconCloudUpload,
  IconCoins,
  IconCreditCard,
  IconDownload,
  IconEye,
  IconFileText,
  IconFileUpload,
  IconGripHorizontal,
  IconGripVertical,
  IconHome,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLoader2,
  IconLogout,
  IconMessageCircle,
  IconMoonStars,
  IconPencil,
  IconPhoto,
  IconPlayerPlay,
  IconPlus,
  IconPrinter,
  IconQrcode,
  IconSearch,
  IconSearchOff,
  IconSend,
  IconSettings,
  IconShieldCheck,
  IconTag,
  IconToggleLeft,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserCog,
  IconUsers,
  IconWallet,
  IconX
} from '@tabler/icons-react';

const ICONS: Record<string, React.ComponentType<any>> = {
  account_balance: IconBuildingBank,
  account_balance_wallet: IconWallet,
  add: IconPlus,
  add_business: IconBriefcase,
  add_card: IconCoins,
  admin_panel_settings: IconShieldCheck,
  archive: IconArchive,
  arrow_downward: IconArrowDown,
  arrow_upward: IconArrowUp,
  calendar_add_on: IconCalendarMonth,
  calendar_month: IconCalendarMonth,
  calendar_view_week: IconCalendarMonth,
  category: IconTag,
  chat: IconMessageCircle,
  check: IconCheck,
  check_circle: IconCircleCheck,
  chevron_left: IconChevronLeft,
  chevron_right: IconChevronRight,
  close: IconX,
  cloud_upload: IconCloudUpload,
  credit_card: IconCreditCard,
  dark_mode: IconMoonStars,
  data_usage: IconChartPie,
  date_range: IconCalendarMonth,
  delete: IconTrash,
  domain_add: IconBriefcase,
  done_all: IconChecks,
  edit: IconPencil,
  error: IconAlertCircle,
  event: IconCalendarCheck,
  event_repeat: IconCalendarRepeat,
  expand_more: IconChevronDown,
  fact_check: IconClipboardCheck,
  file_download: IconDownload,
  file_upload: IconUpload,
  format_list_bulleted: IconClipboardList,
  forum: IconMessageCircle,
  grid_view: IconLayoutGrid,
  group: IconUsers,
  groups: IconUsers,
  how_to_reg: IconUserCheck,
  image: IconPhoto,
  insights: IconBulb,
  logout: IconLogout,
  manage_accounts: IconUserCog,
  more_horiz: IconGripHorizontal,
  more_vert: IconGripVertical,
  notifications: IconBell,
  notifications_active: IconBell,
  notifications_none: IconBell,
  notifications_off: IconBellOff,
  pause_circle: IconToggleLeft,
  payments: IconCoins,
  pending_actions: IconClipboardList,
  person: IconUser,
  person_add: IconUserCheck,
  person_search: IconSearch,
  picture_as_pdf: IconFileText,
  play_circle: IconPlayerPlay,
  print: IconPrinter,
  progress_activity: IconLoader2,
  qr_code_2: IconQrcode,
  query_stats: IconChartLine,
  receipt_long: IconFileText,
  school: IconBook,
  search: IconSearch,
  search_off: IconSearchOff,
  send: IconSend,
  settings: IconSettings,
  sort: IconAdjustmentsHorizontal,
  storefront: IconHome,
  trending_down: IconTrendingDown,
  trending_up: IconTrendingUp,
  upload: IconFileUpload,
  visibility: IconEye,
  warning: IconAlertTriangle,
  workspace_premium: IconAward,
  dashboard: IconLayoutDashboard
};

interface JisIconProps {
  children?: React.ReactNode;
  className?: string;
  name?: string;
  strokeWidth?: number;
  'aria-hidden'?: boolean | 'true' | 'false';
}

export function JisIcon({ children, name, className = '', strokeWidth = 2, ...props }: JisIconProps) {
  const iconName = useMemo(() => (name || String(children ?? '')).trim(), [children, name]);
  const IconComponent = ICONS[iconName] || IconAlertCircle;

  return (
    <span
      className={`jis3r-icon ${className}`}
      aria-hidden={props['aria-hidden'] ?? true}
    >
      <IconComponent size="1em" color="currentColor" stroke={strokeWidth} />
    </span>
  );
}
